services:
  api:
    build:
      context: .
      target: production

    ports:
    - "${PORT}:${PORT}"
    volumes:
      - /home/sav2748/ssl:/usr/src/app/ssl:ro  # Mount SSL directory to a specific app folder in the container with read-only access
    env_file:
      - .env.production
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}